server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages

springdoc:
  packages-to-scan: package1,package2
  paths-to-match: /v1, /api/balance/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
